config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    get 'list_projects', on: :collection
  end
  devise_for :users

  root to: "posts#index"

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:list_projects, :index, :show]
  before_action :check_permission, except: [:list_projects, :index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @show_banner = true
    @posts = Post.all.where(is_project: false).order(created_at: :desc)
  end

  def list_projects
    @show_banner = true
    @posts = Post.all.where(is_project: true).order(created_at: :desc)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def check_permission
      return if current_user.is_admin
      respond_to do |format|
        format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.', status: :forbidden }
        format.json { head :no_content, status: :forbidden }
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:user_id, :title, :body, :image, :is_project)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!--Import Google Icon Font-->
  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet'  type='text/css'>

  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body>

  <nav>
    <div class="white my-container">
      <%= link_to 'Paulo Soares', posts_path, class: "brand-logo"%>

      <ul class="right hide-on-med-and-down">
        <li><%= link_to 'Posts', posts_path %></li>
        <li><%= link_to 'Projects', list_projects_posts_path %></li>
        <li><%= mail_to 'phsoares.ita@gmail.com', 'Contact' %></li>
        <% if signed_in? %>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
          <% if current_user.is_admin %>
            <li><%= link_to 'New Post', new_post_path %></li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </nav>

  <% if @show_banner %>
    <div class="main-banner"></div>
  <% end %>

  <section class="main">
    <div class="page-content my-container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <div class="row">
        <div class="col s12 m8">
         <%= yield %>
        </div>
        <div class="col s12 m4">
         <article>
           <div class="article-header">
             <h2 class="article-title"><strong>About Me</strong></h2>
           </div>
           <img class="my-image" src="/images/myimg.jpg" alt="Paulo's Image" />
           <div class="article-body my-container">
             <br><br>
             <p>
               I'm a passionate <strong>Full Stack Developer</strong>. I
               use mainly <strong>Ruby</strong>
               and <strong>Javascript</strong> in my projects,
               but I also have experience in another languages like
               Python and C#.
             </p>
           </div>
         </article>
        </div>
      </div>
    </div>
  </section>

  <footer>
    <div class="row">
      <div class="my-container">
        <div class="col s12 m6">
        	<p>Copyright 2016. Designed by Paulo Soares</p>
        </div>
        <div class="col s12 m6">
          <div class="right">
            <%= mail_to 'phsoares.ita@gmail.com', 'Contact' %>
          </div>
        </div>
      </div>
    </div>
  </footer>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :is_project %><br>
    <%= f.check_box :is_project %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<article>

  <div class="article-header">
    <p>
      <time class="article-date" datetime="<%= post.created_at %>">
        <%= post.created_at.to_formatted_s(:long) %>
      </time>
    </p>
    <h1 class="article-title my-container">
      <strong>
        <%= post.title %>
      </strong>
    </h1>
  </div>

  <img class="article-image" src="<%= post.image %>">

  <div class="article-body my-container">
    <% if show_details %>
      <%= raw post.body %>
    <% else %>
      <%= raw truncate(post.body, length: 140, escape: false) %>
    <% end %>
  </div>

  <div class="article-actions">
    <% if !show_details %>
      <%= link_to 'Continue reading', post %>
    <% end %>
    <% if signed_in? and current_user.is_admin %>
      <%= link_to 'Edit', edit_post_path(post) %>
      <% if show_details %>
        <%= link_to 'Back', posts_path %>
      <% end %>
      <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </div>

</article>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= render partial: "post", collection: @posts, as: :post,
            locals: {show_back_action: false, show_details: false}%>

app/views/posts/list_projects.html.erb
<%= render partial: "post", collection: @posts, as: :post,
            locals: {show_back_action: false, show_details: false}%>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<%= render partial: "post",
           locals: {post: @post, show_back_action: true, show_details: true} %>